### ISSUE TITLE
Error with Flame version 1.8

### ISSUE THREAD

**Issue by drakkonne** [ASGAlex/flame_tiled_utils#4]
animation_batch_compiler.dart имеет 4 ошибки с новой версией Flame 1.8.0:
`getSprite()`, `anim.currentIndex` and `anim.currentIndex++`

Это прекрасно лечится созданием нового класса из пакета Flame SpriteAnimationTicker:

`SpriteAnimationTicker ticker = SpriteAnimationTicker(anim);`
`while (ticker.currentIndex < anim.frames.length) {`
`ticker.currentIndex++;`
`}`
Теперь мета данные перенесли из анимации в этот класс
В остальном либа просто великолепная

**Comment by ASGAlex** [comment]
fixed
